/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createWeatherForecastDataFromDiscriminatorValue, TestEnum, type WeatherForecastData } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /weatherforecast
 */
export interface WeatherforecastRequestBuilder extends BaseRequestBuilder<WeatherforecastRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WeatherForecastData>}
     */
     get(requestConfiguration?: RequestConfiguration<WeatherforecastRequestBuilderGetQueryParameters> | undefined) : Promise<WeatherForecastData | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WeatherforecastRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface WeatherforecastRequestBuilderGetQueryParameters {
    x?: TestEnum;
}
/**
 * Uri template for the request builder.
 */
export const WeatherforecastRequestBuilderUriTemplate = "{+baseurl}/weatherforecast?x={x}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WeatherforecastRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WeatherforecastRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWeatherForecastDataFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
